// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtB7O31ZetbrUMXPjM94yF3Q-vHFfNtyY',
    appId: '1:1050276192544:web:11a4e9c881f204e928f745',
    messagingSenderId: '1050276192544',
    projectId: 'menuservex',
    authDomain: 'menuservex.firebaseapp.com',
    storageBucket: 'menuservex.firebasestorage.app',
    measurementId: 'G-8MFXFJKKML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9S9UXSFCOPGvtK5jbkOjGRq2gl8E_zLo',
    appId: '1:1050276192544:android:79b4443e215d22f228f745',
    messagingSenderId: '1050276192544',
    projectId: 'menuservex',
    storageBucket: 'menuservex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR5TCDrT3jVbH3TaPP4MHZh9wgXgjzFfU',
    appId: '1:1050276192544:ios:44de6bf4a76465db28f745',
    messagingSenderId: '1050276192544',
    projectId: 'menuservex',
    storageBucket: 'menuservex.firebasestorage.app',
    iosBundleId: 'com.example.menuServex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR5TCDrT3jVbH3TaPP4MHZh9wgXgjzFfU',
    appId: '1:1050276192544:ios:44de6bf4a76465db28f745',
    messagingSenderId: '1050276192544',
    projectId: 'menuservex',
    storageBucket: 'menuservex.firebasestorage.app',
    iosBundleId: 'com.example.menuServex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtB7O31ZetbrUMXPjM94yF3Q-vHFfNtyY',
    appId: '1:1050276192544:web:c3d5ac5917df140528f745',
    messagingSenderId: '1050276192544',
    projectId: 'menuservex',
    authDomain: 'menuservex.firebaseapp.com',
    storageBucket: 'menuservex.firebasestorage.app',
    measurementId: 'G-EHP90QPG80',
  );
}
