// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbUhpGnFnbUpGs4hOpUShAWIh8Y5YVBcc',
    appId: '1:488203891195:web:19df7764319e2cea5f5b5e',
    messagingSenderId: '488203891195',
    projectId: 'menuservex-bb2db',
    authDomain: 'menuservex-bb2db.firebaseapp.com',
    storageBucket: 'menuservex-bb2db.firebasestorage.app',
    measurementId: 'G-226YDEH4H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9lkFwvKDBOch7oNDBUd_jRY8JK4D3xkQ',
    appId: '1:488203891195:android:34d7419e8bc6eba05f5b5e',
    messagingSenderId: '488203891195',
    projectId: 'menuservex-bb2db',
    storageBucket: 'menuservex-bb2db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVTBzbrKmHbfe6EifjQhUcn2re325qONY',
    appId: '1:488203891195:ios:6499e1ca222ce82d5f5b5e',
    messagingSenderId: '488203891195',
    projectId: 'menuservex-bb2db',
    storageBucket: 'menuservex-bb2db.firebasestorage.app',
    iosBundleId: 'com.example.menuServex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVTBzbrKmHbfe6EifjQhUcn2re325qONY',
    appId: '1:488203891195:ios:6499e1ca222ce82d5f5b5e',
    messagingSenderId: '488203891195',
    projectId: 'menuservex-bb2db',
    storageBucket: 'menuservex-bb2db.firebasestorage.app',
    iosBundleId: 'com.example.menuServex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbUhpGnFnbUpGs4hOpUShAWIh8Y5YVBcc',
    appId: '1:488203891195:web:429ae5cae10dcfa55f5b5e',
    messagingSenderId: '488203891195',
    projectId: 'menuservex-bb2db',
    authDomain: 'menuservex-bb2db.firebaseapp.com',
    storageBucket: 'menuservex-bb2db.firebasestorage.app',
    measurementId: 'G-5S8J2WKSVP',
  );
}
